### ISSUE TITLE
gooey shapes

### ISSUE THREAD

**Issue by rupl** [rupl/bustashape#16]
This might have to be a global mode or something, but making shapes be globby or gooey. 

example: http://codepen.io/lbebber/pen/lFdHu

**Comment by afragon** [comment]
Really nice feature! I think defiantly this can be an interesting add-on! It makes it more interesting for people that are just "watching" the art piece

**Comment by rupl** [comment]
I gave this a go last night and unfortunately it only works for very small shapes like in the demo :frowning: 

using the default 200x200 shape just looked weird and when I made the shapes bigger. oh well.
